apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rfc-template
  title: RFC Template
  description: template used for rfc
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Choose
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: dynamic default value
      required:
        - title
      properties:
        title:
          title: Name
          type: string
          description: Name of the App
          default: ${{ parameters.repoUrl }}

  steps:
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}


  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}